### ISSUE TITLE
 An ImageView displays two dynamic webp resources with round-corner frame transformation When multiple dynamic webp resources are displayed in the list

### ISSUE THREAD

**Issue by liusgh** [roths/GlideWebpSupport#10]
我们的项目需要对动态webp做圆角显示，采用的方法是指定帧转换为round corner（目前库中默认是Transformation<Bitmap> unitTransformation = UnitTransformation.get();）发现列表中有两张以上webp资源同时播放时，会出现同一个ImageView中交叉播放两张资源的现象

**Comment by roths** [comment]
项目不再维护，推荐使用这个https://github.com/zjupure/GlideWebpDecoder
