### ISSUE TITLE
加载webp动图的时候，某些机型会出现图片抖动的问题

### ISSUE THREAD

**Issue by magic0908** [roths/GlideWebpSupport#11]
感谢作者提供的库
我使用的是glide4.7.1版，在华为p10和小米8上加载动图，图片会抖动
这是某个图片链接http://osscdn.ixingtu.com/musi_file/20181109/d6325e7f740f0604e9c2928267076352.webp
麻烦作者看下

**Comment by roths** [comment]
项目不再维护，推荐使用这个https://github.com/zjupure/GlideWebpDecoder
