### ISSUE TITLE
render frame error

### ISSUE THREAD

**Issue by zjupure** [roths/GlideWebpSupport#3]
`Bitmap getNextFrame()` method in `WebpDecoder` do not consider the frame info width, height, xoffset, yoffset,  and so on. So when render some webp if frame size smaller than the image size, the frame rending is error with wrong zoom or information loss.

Example:
use the `https://www.gstatic.com/webp/animated/1.webp` image and then run the project, the issue is produced.

Thanks for your work and it give me an idea to transplant fresco's native code into Glide for support animated webp and kick out unnecessary so (libimagepipeline.so, libfb_jpegturbo.so) from fresco.

**Comment by OsBelief** [comment]
Excuse me, how to solve this problem

**Comment by zjupure** [comment]
I have rewrite a webp decoder based on libwebp and some code from this project to fix the issue, see [GlideWebpDecoder](https://github.com/zjupure/GlideWebpDecoder) for detail, welcome to try and report issue.

**Comment by roths** [comment]
fixed
