### ISSUE TITLE
推荐一个能播放动态webp的安卓库

### ISSUE THREAD

**Issue by meikaiss** [roths/GlideWebpSupport#6]
链接 ：
  https://github.com/zjupure/GlideWebpDecoder

这个库使用的 glide 4.2 版本， 播放性能很好，最重要的是能播放 动态webp 图片

**Comment by roths** [comment]
可以，有点久没写android了

**Comment by XunMengWinter** [comment]
有哪些坑不？另外作者支持到glide 4.6.1 了，4.7.1还是不支持（就怕每次glide小升级也得更新啊，那么耦合太强了）。

**Comment by XunMengWinter** [comment]
好像4.7.1也是支持的。但在我们公司项目上支持不了- - demo就可以
