### ISSUE TITLE
不支持网络webp图片

### ISSUE THREAD

**Issue by XunMengWinter** [roths/GlideWebpSupport#7]
https://github.com/wefortop/GlideWebpSupport

老铁，看一下。
我fork过去，加了列表与网图测试，发现不支持网络webp图片，chrome打开是动图能行的。

**Comment by roths** [comment]
添加oktthp网络集成库的依赖:
compile "com.github.bumptech.glide:okhttp3-integration:4.6.1"

**Comment by XunMengWinter** [comment]
还是不行，这是一个动图啊，chrome是可以加载的。

**Comment by roths** [comment]
我加了之后可以，能正常加载而且会动，你试一下卸载掉demo重装

**Comment by roths** [comment]
发现问题了，如果设置resize的时候，数据会解析成bytebuffer而不是inputstream，导致没有启动webpdecoer类
